openapi: 3.0.3
info:
  title: Album Management Service API
  description: Internal API contracts for project and album management functionality
  version: 1.0.0

paths:
  /api/projects:
    get:
      summary: List all projects
      operationId: listProjects
      parameters:
        - name: sort
          in: query
          schema:
            type: string
            enum: ['name', 'created_at', 'updated_at']
            default: 'name'
        - name: order
          in: query
          schema:
            type: string
            enum: ['asc', 'desc']
            default: 'asc'
      responses:
        '200':
          description: Projects retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

    post:
      summary: Create new project
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Project name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/projects/{project_id}:
    get:
      summary: Get project by ID
      operationId: getProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update project
      operationId: updateProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectRequest'
      responses:
        '200':
          description: Project updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

    delete:
      summary: Delete project
      operationId: deleteProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Project deleted successfully
        '404':
          description: Project not found

  /api/projects/{project_id}/albums:
    get:
      summary: List albums in project
      operationId: listProjectAlbums
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Albums retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'

    post:
      summary: Create album in project
      operationId: createAlbum
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlbumRequest'
      responses:
        '201':
          description: Album created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'

  /api/albums/{album_id}:
    get:
      summary: Get album by ID
      operationId: getAlbum
      parameters:
        - name: album_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Album retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumWithPhotos'

    put:
      summary: Update album
      operationId: updateAlbum
      parameters:
        - name: album_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlbumRequest'
      responses:
        '200':
          description: Album updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'

    delete:
      summary: Delete album
      operationId: deleteAlbum
      parameters:
        - name: album_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Album deleted successfully

  /api/albums/reorder:
    post:
      summary: Reorder albums within project
      operationId: reorderAlbums
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReorderAlbumsRequest'
      responses:
        '200':
          description: Albums reordered successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'

  /api/albums/{album_id}/photos:
    get:
      summary: List photos in album
      operationId: listAlbumPhotos
      parameters:
        - name: album_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Photos retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Photo'

    post:
      summary: Add photo to album
      operationId: addPhotoToAlbum
      parameters:
        - name: album_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPhotoRequest'
      responses:
        '201':
          description: Photo added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photo'

components:
  schemas:
    Project:
      type: object
      required:
        - id
        - name
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique project identifier
        name:
          type: string
          description: Project name
        description:
          type: string
          description: Project description
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Album:
      type: object
      required:
        - id
        - project_id
        - name
        - display_order
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique album identifier
        project_id:
          type: string
          description: Parent project ID
        name:
          type: string
          description: Album name
        display_order:
          type: integer
          description: Order within project
        description:
          type: string
          description: Album description
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    AlbumWithPhotos:
      allOf:
        - $ref: '#/components/schemas/Album'
        - type: object
          properties:
            photos:
              type: array
              items:
                $ref: '#/components/schemas/Photo'

    Photo:
      type: object
      required:
        - id
        - album_id
        - prompt
        - fal_url
        - model_name
        - display_order
        - created_at
      properties:
        id:
          type: string
          description: Unique photo identifier
        album_id:
          type: string
          description: Parent album ID
        prompt:
          type: string
          description: Generation prompt
        fal_url:
          type: string
          format: uri
          description: Image URL
        model_name:
          type: string
          description: AI model used
        display_order:
          type: integer
          description: Order within album
        generation_params:
          type: string
          description: JSON generation parameters
        file_size:
          type: integer
          description: File size in bytes
        dimensions:
          type: string
          description: Image dimensions
        created_at:
          type: string
          format: date-time

    CreateProjectRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Project name
        description:
          type: string
          maxLength: 500
          description: Project description

    UpdateProjectRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500

    CreateAlbumRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Album name
        description:
          type: string
          maxLength: 500
          description: Album description

    UpdateAlbumRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500

    ReorderAlbumsRequest:
      type: object
      required:
        - project_id
        - album_orders
      properties:
        project_id:
          type: string
          description: Project containing albums
        album_orders:
          type: array
          items:
            type: object
            required:
              - album_id
              - display_order
            properties:
              album_id:
                type: string
              display_order:
                type: integer

    AddPhotoRequest:
      type: object
      required:
        - photo_id
      properties:
        photo_id:
          type: string
          description: ID of existing generated photo
        display_order:
          type: integer
          description: Position in album (optional, appends if not provided)

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error context