openapi: 3.0.3
info:
  title: Projects API
  description: Manages project CRUD operations and organization
  version: 1.0.0

paths:
  /api/projects:
    get:
      summary: List all projects with album counts
      operationId: getProjects
      responses:
        '200':
          description: List of projects with album counts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectWithAlbumCount'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectError'

    post:
      summary: Create new project
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectError'

  /api/projects/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    put:
      summary: Update project details
      operationId: updateProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectRequest'
      responses:
        '200':
          description: Project updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectError'

    delete:
      summary: Delete project (cascades to albums and photos)
      operationId: deleteProject
      responses:
        '204':
          description: Project deleted successfully
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectError'

  /api/projects/reorder:
    put:
      summary: Reorder projects
      operationId: reorderProjects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReorderProjectsRequest'
      responses:
        '200':
          description: Projects reordered successfully
        '400':
          description: Invalid reorder data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectError'

components:
  schemas:
    Project:
      type: object
      required:
        - id
        - name
        - displayOrder
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
        displayOrder:
          type: integer
          minimum: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProjectWithAlbumCount:
      allOf:
        - $ref: '#/components/schemas/Project'
        - type: object
          required:
            - albumCount
          properties:
            albumCount:
              type: integer
              minimum: 0
            albums:
              type: array
              items:
                $ref: '#/components/schemas/AlbumPreview'

    AlbumPreview:
      type: object
      required:
        - id
        - name
        - photoCount
        - displayOrder
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        photoCount:
          type: integer
          minimum: 0
        coverPhotoUrl:
          type: string
          format: uri
        displayOrder:
          type: integer
          minimum: 0

    CreateProjectRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'

    UpdateProjectRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'

    ReorderProjectsRequest:
      type: object
      required:
        - projectOrders
      properties:
        projectOrders:
          type: array
          items:
            type: object
            required:
              - id
              - displayOrder
            properties:
              id:
                type: string
                format: uuid
              displayOrder:
                type: integer
                minimum: 0

    ProjectError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - PROJECT_NOT_FOUND
            - INVALID_NAME
            - DUPLICATE_ORDER
        message:
          type: string
        field:
          type: string
